__all__ = ['INTER_OK', 'ERR_PARAM', 'ERR_INPUT', 'ERR_OUTPUT', 'ERR_FORMAT', 
'ERR_STRUCT', 'ERR_SEMAN', 'ERR_TYPES', 'ERR_UNDECLVAR', 'ERR_NOFRAME', 
'ERR_UNDEFVAR', 'ERR_VALUE', 'ERR_STRING']

INTER_OK = 0
ERR_PARAM = 10
ERR_INPUT = 11
ERR_OUTPUT = 12
ERR_FORMAT = 31
ERR_STRUCT = 32
ERR_SEMAN = 52
ERR_TYPES = 53
ERR_UNDECLVAR = 54
ERR_NOFRAME = 55
ERR_UNDEFVAR = 56
ERR_VALUE = 57
ERR_STRING = 58